name: CI

on:
  push:
    branches:
      - main
      #- feature/image-feed/cache-feed-use-case

jobs:

  # Второе задание: Сборка и тестирование для macOS
  build-and-test-macos:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Display Xcode version
        run: xcodebuild -version

      - name: List available Xcode versions
        run: |
          xcode-select -p
          ls /Applications | grep Xcode

      - name: Select Xcode
        run: |
          # sudo xcode-select -s /Applications/Xcode.app
          sudo xcode-select -s /Applications/Xcode_16.2.app
          echo ">> availale xcode versions"
          xcode-select -p
          echo ">> current version"
          xcodebuild -version

      - name: Build and Test macOS
        run: |

          echo "Now Current directory is:"
          pwd
          ls -la

          xcodebuild clean build test \
          -project EssentialFeed.xcodeproj \
          -scheme "CI" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          -sdk macosx \
          -destination "platform=macOS"
